import { Link } from "react-router-dom";
import "./LegalPage.css";

export default function PrivacyPolicyPage() {
  return (
    <div className="legal-page">
      <div className="legal-header">
        <Link to="/" className="legal-back-link">← Back to Noctu</Link>
      </div>
      <div className="legal-content">
        <h1>Noctu Privacy Policy</h1>
        <p className="legal-effective-date"><strong>Effective Date:</strong> August 19, 2026</p>
      <p key={0}>{"Noctu (\""}<strong>{"Noctu"}</strong>{",\" \""}<strong>{"we"}</strong>{",\" \""}<strong>{"us"}</strong>{",\" or \""}<strong>{"our"}</strong>{"\") is operated by Marq Georgia, a sole proprietor based in Florida, United States. This Privacy Policy explains how we collect, use, disclose, retain, and protect information when you use our website, applications, membership and loyalty services, QR-code check-in features, and related services (collectively, the \""}<strong>{"Services"}</strong>{"\")."}</p>
      <p key={1}>{"Please read this Privacy Policy carefully. By using the Services, you acknowledge the practices described here. If you do not agree with this Privacy Policy, do not use the Services."}</p>
      <h2 key={2}>{"1. Information We Collect"}</h2>
      <p key={3}>{"We collect information you provide to us, information generated through use of the Services, and information received from our service providers and participating venues."}</p>
      <h3 key={4}>{"A. Account and Profile Information"}</h3>
      <p key={5}>{"When you create a member account, we may collect:"}</p>
      <ul className="legal-list"><li key={6_0}>{"Full name;"}</li><li key={6_1}>{"Email address;"}</li><li key={6_2}>{"Phone number;"}</li><li key={6_3}>{"Date of birth or birthday information;"}</li><li key={6_4}>{"Password (stored in protected form and not in readable plaintext);"}</li><li key={6_5}>{"Membership tier, account settings, and communication preferences; and"}</li><li key={6_6}>{"Referral code and referral activity."}</li></ul>
      <p key={13}>{"If you create or administer a club-owner or venue account, we may also collect your business name, your name and contact details, account credentials, venue details, and information needed to provide the business-facing features of the Services."}</p>
      <h3 key={14}>{"B. Loyalty, Venue, and Activity Information"}</h3>
      <p key={15}>{"When your Noctu QR code is scanned at a participating club, bar, or other venue, we collect information associated with the scan, such as:"}</p>
      <ul className="legal-list"><li key={10_0}>{"Scan type or event (for example, entry, check-in, reward, or loyalty activity);"}</li><li key={10_1}>{"Participating venue or club name;"}</li><li key={10_2}>{"Date and time of the scan; and"}</li><li key={10_3}>{"Membership, loyalty-points, reward, or tier activity connected to the scan."}</li></ul>
      <p key={20}>{"This information reflects activity at participating venues. We do not claim that QR scans provide continuous, precise device location tracking. However, a scan may indicate that your QR code was presented at the identified venue at the time recorded."}</p>
      <h3 key={21}>{"C. Payment and Subscription Information"}</h3>
      <p key={22}>{"Paid membership subscriptions are processed through Stripe-hosted checkout and Stripe's payment services. We do "}<strong>{"not"}</strong>{" collect or store your complete payment-card number. Stripe may collect payment-card details, billing information, payment status, and other payment-related information necessary to process your subscription. We may receive limited information from Stripe, such as your subscription status, payment confirmation, payment method type, customer identifier, transaction amount, and billing-related status information."}</p>
      <h3 key={23}>{"D. Communications Information"}</h3>
      <p key={24}>{"If you contact us, respond to a message, request support, or otherwise communicate with us, we may collect the content of your communication and related details. We may also maintain records of SMS consent, opt-out requests, delivery status, and messaging interactions."}</p>
      <h3 key={25}>{"E. Device, Log, and Cookie Information"}</h3>
      <p key={26}>{"When you visit or use the Services, we may automatically collect technical and usage information, including IP address, browser type, device type, operating system, pages or features viewed, referring URLs, timestamps, and diagnostic logs. We may use cookies, local storage, pixels, or similar technologies to keep you signed in, remember preferences, operate and secure the Services, understand usage, and improve performance."}</p>
      <p key={27}>{"You can usually configure your browser to refuse or remove cookies. Some parts of the Services may not function properly if you do so."}</p>
      <h2 key={28}>{"2. How We Use Information"}</h2>
      <p key={29}>{"We may use the information described in this Privacy Policy to:"}</p>
      <ul className="legal-list"><li key={21_0}>{"Create, maintain, authenticate, and secure your account;"}</li><li key={21_1}>{"Provide memberships, QR-code scanning, loyalty points, rewards, referrals, and related Services;"}</li><li key={21_2}>{"Confirm eligibility, manage member tiers, and administer subscriptions;"}</li><li key={21_3}>{"Process payments and prevent fraudulent or unauthorized transactions;"}</li><li key={21_4}>{"Send transactional or service-related notices, including account, subscription, check-in, table-ready, security, and support messages;"}</li><li key={21_5}>{"Send SMS and other marketing communications when permitted by law and consistent with your choices;"}</li><li key={21_6}>{"Operate club-owner features, including member lists, messaging tools, and revenue dashboards;"}</li><li key={21_7}>{"Analyze use of the Services, troubleshoot problems, maintain security, and improve our offerings;"}</li><li key={21_8}>{"Enforce our Terms of Service and other policies; and"}</li><li key={21_9}>{"Comply with applicable law, legal process, or enforceable governmental requests."}</li></ul>
      <h2 key={40}>{"3. SMS Messages and Your Choices"}</h2>
      <p key={41}>{"By providing your phone number, you consent to receive SMS messages from Noctu including promotional and transactional messages. Message frequency varies. Message and data rates may apply. Reply "}<strong>{"STOP"}</strong>{" to opt out, "}<strong>{"HELP"}</strong>{" for help."}</p>
      <p key={42}>{"We use Twilio and may use other messaging providers to send and administer SMS messages. We will maintain records of your consent and opt-out requests as required or appropriate. Consent to receive marketing text messages is not a condition of purchasing any goods or services, except where permitted by applicable law. You may opt out of promotional SMS messages at any time by replying "}<strong>{"STOP"}</strong>{". After you opt out, you may still receive messages necessary to confirm your opt-out and, where permitted, certain non-marketing or account-related communications."}</p>
      <p key={43}>{"If you separately agree to a checkbox, written disclosure, or other opt-in mechanism for an SMS program, that consent applies in addition to this Privacy Policy. Please provide a mobile number only if you are the account holder or have authorization to enroll that number."}</p>
      <h2 key={44}>{"4. How We Share Information"}</h2>
      <p key={45}>{"We do not sell your personal information for money. We may share personal information as follows:"}</p>
      <ul className="legal-list"><li key={28_0}><strong>{"Participating venues and club owners."}</strong>{" Information necessary to operate a venue's use of Noctu may be available to the relevant participating venue or its authorized account users. This can include information about members who have interacted with that venue through the Services, such as name, contact information, membership or loyalty status, QR-scan activity at that venue, and messaging interactions, to the extent enabled by the Services."}</li><li key={28_1}><strong>{"Service providers."}</strong>{" We share information with vendors that provide services on our behalf, including Stripe for subscription and payment processing; Twilio for SMS delivery and messaging administration; Firebase/Firestore and Google Cloud infrastructure for data storage, authentication, hosting, analytics, security, and related cloud services; and providers of customer support, security, and technical services."}</li><li key={28_2}><strong>{"Business transfers."}</strong>{" Information may be disclosed in connection with a merger, financing, acquisition, sale of assets, reorganization, bankruptcy, or similar transaction, subject to applicable law."}</li><li key={28_3}><strong>{"Legal, safety, and rights protection."}</strong>{" We may disclose information when we reasonably believe it is necessary to comply with law, respond to lawful process, protect the rights, property, security, or safety of Noctu, our users, venues, or the public, or investigate suspected fraud, abuse, or violations of our policies."}</li><li key={28_4}><strong>{"With your direction or consent."}</strong>{" We may share information when you ask us to do so or otherwise consent."}</li></ul>
      <p key={51}>{"Our service providers may process information in the United States and other countries where they or their service providers operate. Their handling of information may also be governed by their own privacy notices and contractual commitments."}</p>
      <h2 key={52}>{"5. Club Owner and Venue Access"}</h2>
      <p key={53}>{"If you participate in a venue's Noctu program, authorized users of that venue's business account may be able to view and use information associated with your interactions with that venue. Venue access is intended to support membership administration, loyalty programs, customer service, venue communications, and business analytics. We require club owners and other business users to use such information only for authorized, lawful purposes and in accordance with our Terms of Service."}</p>
      <p key={54}>{"Venue operators may independently collect information from you outside Noctu (for example, through their own reservation, entry, or point-of-sale systems). Noctu is not responsible for the privacy practices of venues or other third parties outside the Services."}</p>
      <h2 key={55}>{"6. Referrals"}</h2>
      <p key={56}>{"Noctu may assign or allow you to create a referral code that you can share with others. Referral codes are designed to identify the referring member and may be visible to people with whom you share them and to Noctu. Do not include sensitive personal information in a referral code or share a code in a way that violates another person's privacy or applicable law."}</p>
      <h2 key={57}>{"7. Your Privacy Choices and Rights"}</h2>
      <p key={58}>{"Subject to applicable law, you may request to:"}</p>
      <ul className="legal-list"><li key={37_0}>{"Access personal information we hold about you;"}</li><li key={37_1}>{"Correct inaccurate or incomplete personal information;"}</li><li key={37_2}>{"Delete personal information we hold about you;"}</li><li key={37_3}>{"Receive information about our personal-information practices; or"}</li><li key={37_4}>{"Opt out of marketing emails or text messages."}</li></ul>
      <p key={64}>{"To submit a request, contact us at "}<strong>{"support@noctu.cc"}</strong>{" with the subject line \"Privacy Request.\" We may need to verify your identity before completing a request. Your rights may be limited in circumstances permitted by law, including where we need to retain information to complete a transaction, comply with a legal obligation, resolve disputes, enforce agreements, protect security, or prevent fraud."}</p>
      <p key={65}>{"You can opt out of promotional emails by using the unsubscribe link in the email, and of promotional SMS by replying "}<strong>{"STOP"}</strong>{". These choices do not necessarily prevent us from sending necessary transactional or service-related messages."}</p>
      <h2 key={66}>{"8. Data Retention"}</h2>
      <p key={67}>{"We retain personal information only for as long as reasonably necessary for the purposes described in this Privacy Policy, including to provide and improve the Services, maintain business and loyalty records, meet legal, accounting, tax, and reporting requirements, resolve disputes, enforce our agreements, and maintain security. Retention periods vary based on the type of information, the nature of our relationship with you, and legal obligations."}</p>
      <p key={68}>{"When information is no longer needed, we will delete, de-identify, aggregate, or otherwise dispose of it in accordance with our practices and applicable law. Backup copies may persist for a limited period before being overwritten."}</p>
      <h2 key={69}>{"9. Security"}</h2>
      <p key={70}>{"We use reasonable administrative, technical, and organizational measures designed to protect personal information. These measures include the use of service providers such as Firebase/Firestore and Google Cloud infrastructure. No system, transmission, or storage method is completely secure, and we cannot guarantee absolute security. You are responsible for keeping your account credentials confidential and promptly notifying us of suspected unauthorized access."}</p>
      <h2 key={71}>{"10. Children's Privacy"}</h2>
      <p key={72}>{"The Services are intended for adults and are not directed to children. You must be at least 18 years old to use the Services, and particular venues or events may impose a higher age requirement, including 21 or older for alcohol-related access. We do not knowingly collect personal information from anyone under 18. If you believe that a person under 18 has provided us personal information, contact us at "}<strong>{"support@noctu.cc"}</strong>{", and we will take appropriate steps to delete it."}</p>
      <h2 key={73}>{"11. Third-Party Links and Services"}</h2>
      <p key={74}>{"The Services may link to or integrate with third-party services, including Stripe, Twilio, participating venues, and social or other online services. Their privacy practices are governed by their own policies, not this Privacy Policy. We encourage you to review those policies before providing them information."}</p>
      <h2 key={75}>{"12. Changes to This Privacy Policy"}</h2>
      <p key={76}>{"We may update this Privacy Policy from time to time. We will post the updated version on the Services and change the Effective Date above. If we make material changes, we may provide additional notice as required by law. Your continued use of the Services after an updated Privacy Policy becomes effective means that you acknowledge the updated Policy."}</p>
      <h2 key={77}>{"13. Contact Us"}</h2>
      <p key={78}>{"For questions, requests, or concerns about this Privacy Policy or our privacy practices, contact:"}</p>
      <p key={79}>{"Marq Georgia"}</p>
      <p key={80}>{"support@noctu.cc"}</p>
      <p key={81}>{"[Mailing Address, if applicable]"}</p>
      <p key={82}>{"Florida, United States"}</p>
      </div>
    </div>
  );
}
