import { Link } from "react-router-dom";
import "./LegalPage.css";

export default function TermsOfServicePage() {
  return (
    <div className="legal-page">
      <div className="legal-header">
        <Link to="/" className="legal-back-link">← Back to Noctu</Link>
      </div>
      <div className="legal-content">
        <h1>Noctu Terms of Service</h1>
        <p className="legal-effective-date"><strong>Effective Date:</strong> August 19, 2026</p>
      <p key={0}>{"These Terms of Service (\""}<strong>{"Terms"}</strong>{"\") are a legal agreement between you and Marq Georgia, a sole proprietor based in Florida, United States (\""}<strong>{"Noctu"}</strong>{",\" \""}<strong>{"we"}</strong>{",\" \""}<strong>{"us"}</strong>{",\" or \""}<strong>{"our"}</strong>{"\"). These Terms govern your access to and use of noctu.cc, our applications, membership and loyalty features, QR-code check-in features, subscriptions, business tools, and related services (collectively, the \""}<strong>{"Services"}</strong>{"\")."}</p>
      <p key={1}>{"By creating an account, subscribing, accessing, or using the Services, you agree to these Terms and our Privacy Policy. If you do not agree, do not use the Services."}</p>
      <h2 key={2}>{"1. Eligibility"}</h2>
      <p key={3}>{"You must be at least 18 years old to create an account or use the Services. The Services are not directed to anyone under 18."}</p>
      <p key={4}>{"Noctu membership or use of the Services does not guarantee access to any club, bar, event, venue, alcohol, or age-restricted activity. Each participating venue establishes and enforces its own entry requirements, dress codes, conduct rules, identification requirements, capacity limits, reservation terms, and age policies. Many venues and alcohol-related activities may require you to be 21 or older. You are solely responsible for complying with all applicable venue rules and laws."}</p>
      <p key={5}>{"If you use the Services on behalf of a business or other entity, you represent that you have authority to bind that entity to these Terms. In that case, \"you\" includes that entity and its authorized users."}</p>
      <h2 key={6}>{"2. Accounts and Account Security"}</h2>
      <p key={7}>{"You must provide accurate, current, and complete information when creating and maintaining your account. You agree to promptly update information that changes, including your email address, phone number, and date of birth where applicable."}</p>
      <p key={8}>{"You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. Do not share, sell, transfer, or allow another person to use your account or QR code. You must promptly notify us at "}<strong>{"support@noctu.cc"}</strong>{" if you suspect unauthorized account access or misuse."}</p>
      <p key={9}>{"We may require identity, age, or account verification and may suspend or restrict access until verification is completed."}</p>
      <h2 key={10}>{"3. Noctu Membership, QR Codes, and Participating Venues"}</h2>
      <p key={11}>{"Noctu provides membership, loyalty, referral, and venue-engagement features. A Noctu QR code may be scanned at participating venues to record eligible activity and award loyalty points or other benefits."}</p>
      <p key={12}>{"Venue participation, access, availability, offerings, rewards, and acceptance of QR scans are determined by the applicable venue and may change without notice. Noctu does not own, operate, control, or guarantee participating venues, their events, their employees, their security practices, their services, or their compliance with laws. Your attendance at or interaction with a venue is at your own risk and is subject to the venue's terms and policies."}</p>
      <p key={13}>{"You must not duplicate, alter, forge, photograph for another person's use, sell, distribute, interfere with, or misuse a QR code. We may void points, rewards, or benefits and suspend or terminate accounts for suspected fraud, duplicate scans, sharing, manipulation, or other misuse."}</p>
      <h2 key={14}>{"4. Subscription Plans, Billing, and Cancellation"}</h2>
      <h3 key={15}>{"A. Paid Plans"}</h3>
      <p key={16}>{"Noctu may offer paid recurring membership tiers, including:"}</p>
      <ul className="legal-list"><li key={17_0}><strong>{"Starter:"}</strong>{" $9.99 per month;"}</li><li key={17_1}><strong>{"VIP:"}</strong>{" $19.99 per month; and"}</li><li key={17_2}><strong>{"Elite:"}</strong>{" $49.99 per month."}</li></ul>
      <p key={20}>{"Prices, features, benefits, and available tiers may change as described in these Terms or as disclosed at checkout. Taxes may apply where required."}</p>
      <h3 key={21}>{"B. Recurring Billing Through Stripe"}</h3>
      <p key={22}>{"Paid subscriptions are processed through Stripe-hosted checkout and Stripe's payment services. By starting a paid subscription, you authorize Stripe and Noctu to charge the payment method you provide for the subscription price, applicable taxes, and any other disclosed charges on a recurring monthly basis until you cancel. We do not store your complete payment-card number."}</p>
      <p key={23}>{"Your subscription will automatically renew at the end of each billing period unless you cancel before the next renewal date. Stripe's terms and privacy policy may also apply to payment processing."}</p>
      <h3 key={24}>{"C. Cancellation"}</h3>
      <p key={25}>{"You may cancel your subscription through your account settings, the Stripe customer portal if available, or by contacting "}<strong>{"support@noctu.cc"}</strong>{". To avoid charges for the next billing period, cancel before your then-current billing period ends. Unless stated otherwise at the time of purchase, cancellation takes effect at the end of the current paid billing period, and you may continue to use paid features until that period ends."}</p>
      <p key={26}>{"Deleting the app, ceasing use of the Services, or removing a payment method does not by itself cancel your subscription."}</p>
      <h3 key={27}>{"D. Refunds"}</h3>
      <p key={28}>{"Except where required by applicable law or expressly stated in writing by Noctu, payments are nonrefundable and we do not provide refunds or credits for partial billing periods, unused time, unused membership benefits, or accidental non-use. If you believe a charge was made in error, contact us promptly at "}<strong>{"support@noctu.cc"}</strong>{" so we can review the matter."}</p>
      <h3 key={29}>{"E. Payment Problems and Price Changes"}</h3>
      <p key={30}>{"If a payment fails, we may retry the payment method, suspend paid features, downgrade or cancel your subscription, or take other actions permitted by law. You are responsible for keeping your billing information current."}</p>
      <p key={31}>{"We may change subscription prices or features by providing advance notice through the Services, email, or another reasonable method. A price change will apply no earlier than your next renewal after the stated notice period, unless otherwise required or permitted by law. If you do not agree with a change, you must cancel before it takes effect."}</p>
      <h2 key={32}>{"5. Loyalty Points, Rewards, and Referrals"}</h2>
      <p key={33}>{"Loyalty points, rewards, credits, promotions, referral benefits, and similar features (collectively, \""}<strong>{"Benefits"}</strong>{"\") are promotional features offered at our discretion. Benefits:"}</p>
      <ul className="legal-list"><li key={32_0}>{"Have no cash value;"}</li><li key={32_1}>{"Are not property, currency, stored value, or a prepaid payment instrument;"}</li><li key={32_2}>{"May not be sold, purchased, transferred, exchanged, or redeemed for cash except where we expressly allow it;"}</li><li key={32_3}>{"May be subject to expiration dates, eligibility requirements, quantity limits, venue restrictions, and additional terms; and"}</li><li key={32_4}>{"May be corrected, revoked, modified, suspended, or discontinued by Noctu or a venue at any time, to the extent permitted by law."}</li></ul>
      <p key={39}>{"We may withhold, reverse, or void Benefits that we reasonably believe were obtained through error, fraud, abuse, duplicate or improper scans, account sharing, referrals that violate these Terms, or other unauthorized activity. Noctu does not guarantee that any particular benefit will be available, accepted by a venue, or have a particular value."}</p>
      <p key={40}>{"Referral codes may be shared only for legitimate personal referrals and lawful promotional purposes. You may not use automated means, spam, misleading statements, paid placements without authorization, or impersonation to obtain referral benefits."}</p>
      <h2 key={41}>{"6. SMS, Email, and Other Communications"}</h2>
      <p key={42}>{"By providing your phone number, you consent to receive SMS messages from Noctu including promotional and transactional messages. Message frequency varies. Message and data rates may apply. Reply "}<strong>{"STOP"}</strong>{" to opt out, "}<strong>{"HELP"}</strong>{" for help."}</p>
      <p key={43}>{"We may send texts about birthdays, membership activity, table-ready alerts, account or subscription matters, and promotions, subject to applicable law and your communication preferences. You may opt out of promotional SMS messages at any time by replying "}<strong>{"STOP"}</strong>{". Consent to receive marketing text messages is not a condition of purchasing any goods or services, except where permitted by law. You may receive a confirmation message after opting out and may still receive certain non-marketing or legally permitted transactional messages."}</p>
      <p key={44}>{"You agree to provide only a mobile number that you own or are authorized to enroll. You are responsible for charges imposed by your mobile carrier. For assistance, reply "}<strong>{"HELP"}</strong>{" or contact "}<strong>{"support@noctu.cc"}</strong>{"."}</p>
      <p key={45}>{"You also agree that we may send account, legal, subscription, and service-related communications by email, push notification, or other electronic means. You may unsubscribe from marketing emails using the link in the email, but you may not opt out of necessary service-related communications while you maintain an account."}</p>
      <h2 key={46}>{"7. Acceptable Use"}</h2>
      <p key={47}>{"You agree not to, and not to assist or permit anyone else to:"}</p>
      <ul className="legal-list"><li key={42_0}>{"Use the Services unlawfully or in violation of these Terms, venue policies, or applicable laws;"}</li><li key={42_1}>{"Provide false, misleading, or fraudulent account, age, identity, payment, venue, or referral information;"}</li><li key={42_2}>{"Use another person's account, QR code, loyalty points, payment method, or personal information without authorization;"}</li><li key={42_3}>{"Attempt to gain unauthorized access to the Services, accounts, systems, data, APIs, or networks;"}</li><li key={42_4}>{"Interfere with, disrupt, overload, reverse engineer, decompile, circumvent security measures for, or introduce harmful code into the Services, except to the limited extent prohibited by applicable law;"}</li><li key={42_5}>{"Harvest, collect, or use personal information from the Services without authorization;"}</li><li key={42_6}>{"Send spam, unlawful marketing messages, harassing content, deceptive communications, or content that infringes another person's rights;"}</li><li key={42_7}>{"Use the Services to facilitate illegal activity, including underage drinking, unlawful discrimination, threats, violence, or exploitation; or"}</li><li key={42_8}>{"Misrepresent your affiliation with Noctu, a participating venue, or another person or entity."}</li></ul>
      <p key={57}>{"We may investigate suspected violations and take any action we consider appropriate, including removing content, voiding Benefits, suspending access, terminating accounts, and reporting conduct to venues or authorities where appropriate."}</p>
      <h2 key={58}>{"8. Additional Terms for Club Owners and Other Business Users"}</h2>
      <p key={59}>{"If you use Noctu as a club owner, venue operator, or other business user (each, a \""}<strong>{"Business User"}</strong>{"\"), you additionally agree that you will:"}</p>
      <ul className="legal-list"><li key={46_0}>{"Provide accurate business, venue, and account information and keep it current;"}</li><li key={46_1}>{"Use member information, member lists, messaging tools, revenue dashboards, and other business features only for legitimate, authorized business purposes connected to your venue's use of Noctu;"}</li><li key={46_2}>{"Obtain and maintain all notices, consents, permissions, licenses, and legal rights necessary for your collection, use, disclosure, and messaging of personal information;"}</li><li key={46_3}>{"Comply with all applicable privacy, marketing, consumer-protection, anti-spam, telephone, alcohol, licensing, accessibility, employment, and other laws, including laws governing SMS and marketing communications;"}</li><li key={46_4}>{"Send messages only to recipients for whom you have the necessary consent or other lawful basis, honor opt-out requests immediately, and not use Noctu's tools to send unlawful, deceptive, abusive, discriminatory, or unsolicited communications;"}</li><li key={46_5}>{"Keep access credentials secure and limit access to authorized personnel;"}</li><li key={46_6}>{"Ensure that your venue's rules, promotions, rewards, offers, entry decisions, alcohol service, and operations comply with law and do not violate third-party rights; and"}</li><li key={46_7}>{"Not use member information obtained through Noctu to build, sell, rent, disclose, or exploit independent marketing lists except as expressly authorized by the affected person and applicable law."}</li></ul>
      <p key={68}>{"Business Users are independently responsible for their venues, staff, messages, promotions, rewards, customer interactions, records, taxes, and legal compliance. Noctu does not provide legal, tax, alcohol-licensing, or regulatory advice. We may suspend a Business User's access if we reasonably believe the Business User's conduct creates legal, security, reputational, or operational risk."}</p>
      <h2 key={69}>{"9. Intellectual Property and Feedback"}</h2>
      <p key={70}>{"The Services, including their software, design, text, graphics, logos, trademarks, features, and content, are owned by or licensed to Noctu and are protected by applicable intellectual-property laws. Subject to these Terms, Noctu grants you a limited, personal, revocable, nonexclusive, nontransferable right to access and use the Services for their intended purpose."}</p>
      <p key={71}>{"Except as expressly permitted by these Terms, you may not copy, modify, distribute, publicly display, create derivative works from, lease, sell, sublicense, or exploit the Services or any portion of them."}</p>
      <p key={72}>{"If you provide feedback, ideas, or suggestions about the Services, you grant Noctu a worldwide, perpetual, irrevocable, royalty-free right to use and incorporate that feedback without compensation or obligation to you."}</p>
      <h2 key={73}>{"10. Third Parties and Venue Disclaimers"}</h2>
      <p key={74}>{"The Services may integrate with or link to third parties, including Stripe, Twilio, Firebase/Google Cloud services, and participating venues. We do not control and are not responsible for third-party services, content, conduct, availability, privacy practices, goods, services, promotions, entry decisions, injuries, losses, or disputes. Your use of third-party services and attendance at venues are subject to the applicable third party's terms and policies."}</p>
      <p key={75}>{"Noctu is not a ticket seller, alcohol provider, security provider, transportation provider, event organizer, venue operator, or emergency service unless expressly stated otherwise in writing."}</p>
      <h2 key={76}>{"11. Disclaimers"}</h2>
      <p key={77}>{"THE SERVICES ARE PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY LAW, NOCTU DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, QUIET ENJOYMENT, AND AVAILABILITY."}</p>
      <p key={78}>{"WITHOUT LIMITING THE FOREGOING, WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, SECURE, ERROR-FREE, AVAILABLE AT A PARTICULAR TIME OR PLACE, OR THAT QR SCANS, POINTS, REWARDS, VENUE INFORMATION, COMMUNICATIONS, OR SUBSCRIPTION FEATURES WILL ALWAYS BE ACCURATE, COMPLETE, OR AVAILABLE. YOUR USE OF THE SERVICES AND PARTICIPATION AT VENUES IS AT YOUR OWN RISK."}</p>
      <p key={79}>{"Some jurisdictions do not allow certain warranty exclusions, so some of the above exclusions may not apply to you."}</p>
      <h2 key={80}>{"12. Limitation of Liability"}</h2>
      <p key={81}>{"TO THE MAXIMUM EXTENT PERMITTED BY LAW, NOCTU AND ITS OWNER, AFFILIATES, SERVICE PROVIDERS, LICENSORS, AND REPRESENTATIVES WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, CONSEQUENTIAL, OR PUNITIVE DAMAGES; LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS OPPORTUNITY; PERSONAL INJURY; PROPERTY DAMAGE; OR DAMAGES ARISING FROM OR RELATED TO YOUR USE OF OR INABILITY TO USE THE SERVICES, VENUE ATTENDANCE, THIRD-PARTY SERVICES, OR THESE TERMS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES."}</p>
      <p key={82}>{"TO THE MAXIMUM EXTENT PERMITTED BY LAW, NOCTU'S TOTAL LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATED TO THE SERVICES OR THESE TERMS WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO NOCTU FOR THE SERVICES IN THE TWELVE MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM OR (B) ONE HUNDRED U.S. DOLLARS (US $100)."}</p>
      <p key={83}>{"Nothing in these Terms excludes or limits liability that cannot legally be excluded or limited."}</p>
      <h2 key={84}>{"13. Indemnification"}</h2>
      <p key={85}>{"To the maximum extent permitted by law, you will defend, indemnify, and hold harmless Noctu, its owner, affiliates, service providers, licensors, and representatives from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising from or related to: (a) your use or misuse of the Services; (b) your violation of these Terms, applicable law, or another person's rights; (c) your content, messages, referrals, or communications; or (d) for Business Users, your venue operations, personnel, marketing, messages, promotions, rewards, or handling of personal information."}</p>
      <h2 key={86}>{"14. Dispute Resolution; Arbitration; Class-Action Waiver"}</h2>
      <p key={87}><strong>{"Please read this section carefully. It affects legal rights, including the right to bring a lawsuit in court and to have a jury trial."}</strong></p>
      <h3 key={88}>{"A. Informal Resolution First"}</h3>
      <p key={89}>{"Before filing a claim against Noctu, you agree to send a written notice describing the dispute and the relief requested to "}<strong>{"support@noctu.cc"}</strong>{". The parties will attempt in good faith to resolve the dispute informally for at least 30 days after the notice is received."}</p>
      <h3 key={90}>{"B. Binding Individual Arbitration"}</h3>
      <p key={91}>{"Except for the matters excluded below, any dispute, claim, or controversy arising out of or relating to these Terms or the Services that is not resolved informally will be resolved by binding individual arbitration, rather than in court. Arbitration will be administered by the American Arbitration Association (\"AAA\") under its applicable Consumer Arbitration Rules, as modified by these Terms. The arbitration may be conducted remotely, in the county where you live, or in Florida, unless the parties agree otherwise."}</p>
      <p key={92}>{"The Federal Arbitration Act governs the interpretation and enforcement of this arbitration agreement. The arbitrator may award the same individual remedies that a court could award, but only to the extent necessary to provide relief for the individual claim. Judgment on the award may be entered in any court of competent jurisdiction."}</p>
      <h3 key={93}>{"C. Exceptions"}</h3>
      <p key={94}>{"Either party may bring an individual claim in small-claims court if it qualifies. Either party may seek injunctive or equitable relief in a court of competent jurisdiction to protect intellectual-property rights, prevent unauthorized access or misuse of the Services, or address a violation that threatens immediate harm."}</p>
      <h3 key={95}>{"D. Class-Action and Jury-Trial Waiver"}</h3>
      <p key={96}>{"TO THE MAXIMUM EXTENT PERMITTED BY LAW, DISPUTES MUST BE BROUGHT ONLY IN AN INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE, CONSOLIDATED, REPRESENTATIVE, OR PRIVATE-ATTORNEY-GENERAL ACTION. THE ARBITRATOR MAY NOT CONSOLIDATE CLAIMS OR PRESIDE OVER ANY CLASS OR REPRESENTATIVE PROCEEDING. YOU AND NOCTU WAIVE THE RIGHT TO A JURY TRIAL TO THE EXTENT A DISPUTE IS PERMITTED TO PROCEED IN COURT."}</p>
      <p key={97}>{"If a court determines that a particular part of this class-action waiver is unenforceable as to a particular claim, then that claim must be severed and brought in a court of competent jurisdiction, while any remaining claims proceed in individual arbitration to the extent permitted by law."}</p>
      <h2 key={98}>{"15. Suspension and Termination"}</h2>
      <p key={99}>{"You may stop using the Services at any time and may request account deletion as described in our Privacy Policy. Cancellation of a paid subscription is governed by Section 4 and does not automatically erase information that we must or may retain under our Privacy Policy or applicable law."}</p>
      <p key={100}>{"We may suspend, restrict, or terminate your access to all or part of the Services at any time, with or without notice where permitted by law, including if we reasonably believe you violated these Terms, created risk or legal exposure, engaged in fraud or abuse, failed to pay applicable fees, or used the Services in a way that may harm Noctu, venues, users, or third parties."}</p>
      <p key={101}>{"Upon termination, your right to use the Services ends. Provisions that by their nature should survive termination will survive, including provisions regarding payment obligations, intellectual property, disclaimers, limitations of liability, indemnification, dispute resolution, and governing law."}</p>
      <h2 key={102}>{"16. Changes to the Services or These Terms"}</h2>
      <p key={103}>{"We may modify, suspend, or discontinue all or part of the Services, including membership plans, loyalty Benefits, participating venues, QR features, or pricing, at any time to the extent permitted by law."}</p>
      <p key={104}>{"We may update these Terms from time to time. We will post the revised Terms and update the Effective Date above. If changes are material, we may provide additional notice, such as through the Services or by email. The revised Terms become effective on the date stated unless otherwise required by law. Your continued use of the Services after the effective date constitutes acceptance of the revised Terms. If you do not agree to the revised Terms, you must stop using the Services and cancel any subscription before the changes take effect."}</p>
      <h2 key={105}>{"17. Governing Law and Venue"}</h2>
      <p key={106}>{"Except to the extent preempted by the Federal Arbitration Act or other applicable law, these Terms and any dispute arising out of or relating to them or the Services are governed by the laws of the State of Florida, without regard to conflict-of-laws principles."}</p>
      <p key={107}>{"For any dispute that is permitted to proceed in court under these Terms, you and Noctu consent to the exclusive jurisdiction and venue of the state and federal courts located in Florida, unless applicable law requires otherwise."}</p>
      <h2 key={108}>{"18. Miscellaneous"}</h2>
      <p key={109}>{"These Terms, together with the Privacy Policy and any additional terms presented for a specific feature, constitute the entire agreement between you and Noctu regarding the Services and supersede prior agreements relating to the Services."}</p>
      <p key={110}>{"If any provision of these Terms is held invalid or unenforceable, that provision will be enforced to the maximum extent permitted and the remaining provisions will remain in effect. No failure or delay by Noctu to enforce a provision is a waiver of that provision. You may not assign or transfer these Terms or your account without our prior written consent. We may assign these Terms in connection with a merger, acquisition, reorganization, sale of assets, or by operation of law."}</p>
      <h2 key={111}>{"19. Contact Us"}</h2>
      <p key={112}>{"For questions, notices, or concerns about these Terms or the Services, contact:"}</p>
      <p key={113}>{"Marq Georgia"}</p>
      <p key={114}>{"support@noctu.cc"}</p>
      <p key={115}>{"[Mailing Address, if applicable]"}</p>
      <p key={116}>{"Florida, United States"}</p>
      </div>
    </div>
  );
}
